// ignore_for_file: file_names, constant_identifier_names

const COLLAlgs = {
  "AS1" : [
    "R U2 R2 U' R2 U' R2 U2 R U R U R' U R U2 R'",
    "R' U' R U' R' U2' R",
    "L U2 L' U' L U' L'",
    "R U2 R' U' R U' R'",
    "R' U' R U' R' U2 R",
    "L' U' L U' L' U2 L",
  ],
  "AS2" : [
    "R' U2 F' R U R' U' R' F R2 U R' U R",
    "F' L U2 L' F L F' U2 F L'",
    "R' F U2 F' R F R' U2 R F'",
    "R' U' R U' R' U R' D' R U R' D R2",
    "R2 D R' U R D' R' U R' U' R U' R'",
    "L' U' L U' L' U L' D' L U L' D L2",
  ],
  "AS3" : [
    "L R' U' R U L' U2 R' U2 R",
    "F U R' U' R F' U' R' U2 R",
    "R L' U' L U R' U2 L' U2 L",
    "R U R' F' R U2 R' U2 R' F R2 U' R'",
    "R' U' F' R U R' U' R' F R2 U' R' U R",
    "R2 D R' U2 R D' R2 U' R U' R'",
  ],
  "AS4": [
    "R U2 R' U2 R' F R2 U' R' U' R U R' F'",
    "R' U' R U R' F R U R' U' R' F' R2",
    "R U2 R' U2 L' U R U' R' L",
    "R' U' R U' R2 D' R U2 R' D R2",
  ],
  "AS5": [
    "R' U L U' R U L' ",
    "L' U R U' L U R' ",
  ],
  "AS6": [
    "L U2 R' U L' U' R U' L U' L'",
    "R U' R' U2 R U' R' U2 R' D' R U R' D R",
    "R U R' F' R U2 R' U' R U' R' F R U' R'",
  ],
  "H1": [
    "R' U2 R U R' U R U R U R' U R U2 R'",
    "R U2 R' U' R U R' U' R U' R'",
    "R' U' R U' R' U R U' R' U2 R",
    "R' U2 R U R' U' R U R' U R",
    "L U L' U L U' L' U L U2 L'",
  ],
  "H2": [
    "R L' U' L U' L' U L U2 R' U L' U2 L",
    "R' U2 R U2 R2 F' R U R U' R' F U R",
    "F R U' R' U R U2 R' U' R U R' U' F'",
    "L' U R U' L U' R' U2 L' U R U' L R'",
  ],
  "H3": [
    "R' U' R U' R' U' L U' R U L'",
    "R U R2 D' R U2 R' D R U' R U2 R'",
    "R' F' R U2 R U2 R' F U' R U' R'",
    "R U R' U R U L' U R' U' L",
    "R U R2' F R F' L F' L' U L F L'",
  ],
  "H4": [
    "R' U' R' F R F' R' F R F' R' F R F' U R",
    "F U R U' R' U R U' R' U R U' R' F'",
    "F R U R' U' R U R' U' R U R' U' F'",
  ],
  "L1": [
    "R' U' R U' R' U R U' R' U R U' R' U2 R",
    "R U2 R' U2 R' U' R U R U' R' U2 R' U2 R",
    "R U2 R' U' R U R' U' R U R' U' R U' R'",
    "R' U' R U' R' U2 R U' R U R' U R U2 R'",
    "R U R' U R U' R' U R U' R' U R U2' R'",
  ],
  "L2": [
    "L' U2 L' D' L U2 L' D L2",
    "R' U2 R U R2 D' R U R' D R2",
    "R' U2 R' D' R U2 R' D R2",
  ],
  "L3": [
    "L U2 L D L' U2 L D' L2",
    "R' F' R U R' U' R' F R2 U' R' U2 R",
    "R U2 R2 D' R U' R' D R2 U' R'",
    "R U2 R D R' U2 R D' R2",
  ],
  "L4": [
    "R2 D R' U R D' R' U' R'",
    "R U R' U' R' F R U R U' R' F'",
    "R' F' L' F R F' L F",
    "L' R U R' U' L U R U' R'",
    "F R' F' L F R F' L'",
  ],
  "L5": [
    "R L' U' L U R' U' L' U L",
    "L F R F' L' F R' F'",
    "F R U' R' U' R U2 R' U' F'",
    "R2 D' R U' R' D R U R",
    "F' L F R' F' L' F R",
  ],
  "L6": [
    "R' U' R U R' F' R U R' U' R' F R2",
    "R U R' L' U2 R U R' U2 L",
    "F R U R' U' R U' R' U2 R U2 R' U' F'",
    "R' U' R U' F U' R' U' R U F'",
    "F R U R2 F R F' R U' R' F'",
  ],
  "P1": [
    "R U2 R2 U' R2 U' R2 U2 R",
    "L' U2 L2 U L2' U L2 U2 L'",
    "B U L U' L' B' F R U R' U' F'",
  ],
  "P2": [
    "R' U2 R U R' U' R U2 L U' R' U R L'",
    "R U2 R' U' R U' R2 U L U' R U L'",
    "L' U R U' L U R2 U' R U' R' U2 R",
    "R' F2 R U2' R U2' R' F2 U' R U' R'",
    "F U R U' R' U R U' R2 F' R U R U' R'",
  ],
  "P3": [
    "R U2 R' U L' U2 R U R' U' R U' R' L",
    "R F U R2 U2 R2 U R2 U R2 F' R'",
    "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
    "F U R U' R' U R U2 R' U' R U R' F'",
  ],
  "P4": [
    "R U R' U R U2 R' U' R U' L' U R' U' L",
    "R' U2 R U R' U R2 U' L' U R' U' L",
    "L F2 L' U2 L' U2 L F2 U L' U L",
    "R U R' U' R' F R2 U R' U' R U R' U' F'",
  ],
  "P5": [
    "R U R' U F' R U2 R' U2 R' F R",
    "R U R2 F R2 U' R' U' R U R' F' U R U2 R'",
    "L' U R U' L U' R' U' R U' R'",
    "R U' L' U R' U L U L' U L",
    "R U2 R' U R' D' R U2 R' D R2 U' R'",
  ],
  "P6": [
    "R U' R' U2 L' U R U' L R' U2 R U R'",
    "R U D' R U R' D R2 U' R' U' R2' U2' R",
    "R' U' D R' U' R D' R2' U R U R2 U2' R'",
    "F R U' R' U R U R' U R U2 R' U R U R' U R U' R' F",
    "F R2 U' R U' R U' R' U2 R' U R2 F'",
    "R U2 R' U' F' R U2 R' U' R U' R' F R U' R'",
  ],
  "S1": [
    "L U L' U L U2 L'",
    "L' U2 L U L' U L ",
    "R' U2 R U R' U R",
    "R U R' U R U2' R'",
  ],
  "S2": [
    "F R' U' R2 U' R2 U2 R2 U' R' F'",
    "R' U2 R U2 L U' R' U L' R",
    "L' U2 L U2 R U' L' U L R'",
    "R' U' R U R2' F' R U R U' R' F U R",
    "R U R2 F' R U2 R U2 R' F R U' R'",
    "R U R' U R2 D R' U2 R D' R2",
  ],
  "S3": [
    "B' U' R U R' B U R U2 R'",
    "R2 D' R U2 R' D R2 U R' U R",
    "L' R U R' U' L U2 R U2 R'",
  ],
  "S4": [
    "R' U' R U' R2 F' R U R U' R' F U2 R",
    "R2 D' R U' R' D R U' R U R' U R",
    "L F R' F' L' F R F' R U R' U R U2 R'",
    "F R' U2 R F' R' F U2 F' R",
    "R U R' U R U' R D R' U' R D' R2",
  ],
  "S5": [
    "L U' R' U L' U' R",
    "R U' L' U R' U' L",
    "R U' L' U R' U' L",
    "R' L F R F' L' F R' F' R",
  ],
  "S6": [
    "R U R' F' R U R' U R U2 R' F R U' R'",
    "F' R U2 R' U2 R' F2 R U R U' R' F'",
    "R' U2 L U' R U L' U R' U R",
    "F R U' R2 U2 R U R' U R2 U R' F'",
    "R U R' U L' U R U' L U2' R'",
  ],
  "T1":[
    "R U2 R' U' R U' R' U R U R' U R U2 R'",
    "R' U2 R U R' U R2 U2 R' U' R U' R'",
    "R U R' U R U2 R' U' R U2 R' U' R U' R'",
    "R U R2 U' R2 U' R2 U2 R U' R U' R'",
    "R U R' U R U' R' U R' U' R2 U' R2 U2 R",
    "R U R' U R U2 R' L' U' L U' L' U2 L",
  ],
  "T2":[
    "R' U R U2 L' R' U R U' L",
    "R U2 R U2 F2 R F2 L' U2 L U2 R2",
    "R U2 R' U' R' F R2 U' R' U' R U R' F' R U' R'",
    "R' U L' U' L R U2' L' U' L",
    "R' U R U2 L' R' U R U' L",
    "R' U' R' U' R U R' F' R U R' U' R' F R'",
    "R U' R' U2 L R U' R' U L'",
  ],
  "T3":[
    "R' U' R' D' R U R' D R2",
    "F R F' L F R' F' L'",
    "R' F' L F R F' L' F",
  ],
  "T4":[
    "R' F' U' F U R F R' F' R U R U' R'",
    "F U' L' U R2 U' L U R2 F'",
    "F' R' F U2 F' R F R' U2 R",
    "R2 F R F' R U' R' U' r' F R F'",
    "L' U2 R U2 R' U2 L U2 R U2 R'",
    "R F R' U R U2 R' U R U F' R'",
  ],
  "T5":[
    "R U R' U' L' U R U' R' L",
    "R' F' R U R' U' R' F R U R",
    "R U R D R' U' R D' R2",
    "L F R' F' L' F R F'",
  ],
  "T6":[
    "R U R' U R U' L' R' U2 R U R' U2 L",
    "L' U2 L U' R' U L' U' R2 U' L U R'",
    "R2 U R' D' R U R' D R' U' R2 U' R2",
    "R' U' R U' R' U R U R' F' R U R' U' R' F R2",
    "R U R' U' R2 D R' U2 R D' R2' U R U' R'",
    "R' U R2 D L' F2 L D' R2' U' R",
  ],
  "U1":[
    "R U R' U' R U R' U' R U R' U' R2 U R2 U R2 U2 R2",
    "R' F' R U R' U' R' F D' R U R' D R2",
    "R U R' U' R U' R' U2 R U' R' U2 R U R'",
    "R' U' R U' R' U2 R2 U R' U R U2 R'",
    "R U2 R' U' R U' R' L' U2 L U L' U L",
    "R U R' U R U2 R2 U' R U' R' U2 R",
  ],
  "U2":[
    "R' F R' F R2 U' R' U' R U R' F' R U R' U' F' R",
    "R2 F' R U R' U' R' F R2 U' R' U2 R2 U R' U R",
    "R2 F' R U R2 U' R' F R U' R2 U R2 U R'",
    "L' U L U' F R' F R F2 L F' L' F",
    "R U' R2 U' R2 U F U F' R2 F U' F' R",
    "R' U' R F R2 D' R U R' D R2 U' F'",
  ],
  "U3":[
    "R' U L' U R U' L U2 R' U R",
    "R U R' U R U' R' U' R' F R U R U' R' F'",
    "R' U2 R U R2 F' R U R U' R' F R",
    "R U R' U R U' R' U' R' F R U R U' R' F'",
    "R2 D R' U2 R D' R' U2' R'",
    "R' U' R U' R' U2 R2 U' L' U R' U' L",
  ],
  "U4":[
    "R U2 R' U' R' D' R U R' D R U' R U' R'",
    "F R2 U' L' U R2 U' L U F'",
    "R U R' U' R' F2 R2 U' R' U' R U R' F2",
    "R' U2 R F' R' F U2 F' R F",
    "R U2 R' U2 L' U2 R U2 R' U2 L",
    "F U2 R' D' R U2 R' D R F'",
  ],
  "U5":[
    "R2 F' R U R' U' R' F R' U' R2 U2 R2 U R' U R",
    "L2 D' L U2 L' D L U2 L",
    "R2 D' R U2 R' D R U2 R",
    "L U' R U' L' U R' U2 L U' L'",
  ],
  "U6":[
    "R U' R' U' R U2 R2 D' R U R' D R",
    "R2 D' R U R' D R U R U' R' U' R",
    "F U' R' U R U F' R' U2 R",
    "R' D R2 U' R' U' R U2 R2' D' R",
    "R' U2 R U2 R' F' R U R' U' R' F R2",
    "R U' R' U' R U R D R' U R D' R2",
  ]
};
