class DefaultAlgs {
  static final pll = {
    "Aa": "x L2 D2 L' U' L D2 L' U L'",
    "Ab": "x' L2 D2 L U L' D2 L U' L",
    "E": "x' L' U L D' L' U' L D L' U' L D' L' U L D",
    "F": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "Ga": "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    "Gb": "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "Gc": "R2 U' R U' R U R' U R2 U D' R U' R' D",
    "Gd": "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "H": "M2 U M2 U2 M2 U M2",
    "Ja": "x R2 F R F' R U2 r' U r U2",
    "Jb": "R U R' F' R U R' U' R' F R2 U' R'",
    "Na": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "Nb": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "Ra": "R U' R' U' R U R D R' U' R D' R' U2 R'",
    "Rb": "R2 F R U R U' R' F' R U2 R' U2 R",
    "T": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "Ua": "M2 U M U2 M' U M2",
    "Ub": "M2 U' M U2 M' U' M2",
    "V": "R' U R' U' y R' F' R2 U' R' U R' F R F",
    "Y": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "Z": "M' U M2 U M2 U M' U2 M2",
  };
  static final oll = {
    "29": "R U R' U' R U' R' F' U' F R U R'",
    "30": "F R' F R2 U' R' U' R U R' F2",
    "41": "R U R' U R U2 R' F R U R' U' F'",
    "42": "R' U' R U' R' U2 R F R U R' U' F'",
    "39": "L F' L' U' L U F U' L'",
    "40": "R' F R U R' U' F' U R",
    "34": "R U R2 U' R' F R U R U' F'",
    "46": "R' U' R' F R F' U R",
    "28": "r U R' U' r' R U R U' R'",
    "57": "R U R' U' M' U R U' r'",
    "21": "R U2 R' U' R U R' U' R U' R'",
    "22": "R U2 R2 U' R2 U' R2 U2 R",
    "23": "R2 D' R U2 R' D R U2 R",
    "24": "r U R' U' r' F R F'",
    "25": "F' r U R' U' r' F R",
    "26": "R U2 R' U' R U' R'",
    "27": "R U R' U R U2 R'",
    "1": "R U2 R2 F R F' U2 R' F R F'",
    "2": "r U r' U2 r U2 R' U2 R U' r'",
    "3": "r' R2 U R' U r U2 r' U M'",
    "4": "M U' r U2 r' U' R U' R' M'",
    "17": "F R' F' R2 r' U R U' R' U' M'",
    "18": "r U R' U R U2 r2 U' R U' R' U2 r",
    "19": "r' R U R U R' U' M' R' F R F'",
    "20": "r U R' U' M2 U R U' R' U' M'",
    "9": "R U R' U' R' F R2 U R' U' F'",
    "10": "R U R' U R' F R F' R U2 R'",
    "35": "R U2 R2 F R F' R U2 R'",
    "37": "F R' F' R U R U' R'",
    "51": "F U R U' R' U R U' R' F'",
    "52": "R U R' U R U' B U' B' R'",
    "55": "R' F R U R U' R2 F' R2 U' R' U R U R'",
    "56": "r' U' r U' R' U R U' R' U R r' U r",
    "13": "F U R U' R2 F' R U R U' R'",
    "14": "R' F R U R' F' R F U' F'",
    "15": "l' U' l L' U' L U l' U l",
    "16": "r U r' R U R' U' r U' r'",
    "31": "R' U' F U R U' R' F' R",
    "32": "L U F' U' L' U L F L'",
    "43": "F' U' L' U L F",
    "44": "F U R U' R' F'",
    "47": "R' U' R' F R F' R' F R F' U R",
    "48": "F R U R' U' R U R' U' F'",
    "49": "r U' r2 U r2 U r2 U' r",
    "50": "r' U r2 U' r2 U' r2 U r'",
    "53": "l' U2 L U L' U' L U L' U l",
    "54": "r U2 R' U' R U R' U' R U' r'",
    "7": "r U R' U R U2 r'",
    "8": "l' U' L U' L' U2 l",
    "11": "r U R' U R' F R F' R U2 r'",
    "12": "M' R' U' R U' R' U2 R U' R r'",
    "5": "l' U2 L U L' U l",
    "6": "r U2 R' U' R U' r'",
    "33": "R U R' U' R' F R F'",
    "45": "F R U R' U' F'",
    "36": "L' U' L U' L' U L U L F' L' F",
    "38": "R U R' U R U' R' U' R' F R F'",
  };
  static final coll = {
    "AS1": "L' U' L U' L' U2 L",
    "AS2": "R' U2 F' R U R' U' R' F R2 U R' U R",
    "AS3": "R2 D R' U2 R D' R2 U' R U' R'",
    "AS4": "R' U' R U' R2 D' R U2 R' D R2",
    "AS5": "L' U R U' L U R'",
    "AS6": "R U' R' U2 R U' R' U2 R' D' R U R' D R",
    "H1": "R U R' U R U' R' U R U2 R'",
    "H2": "F R U' R' U R U2 R' U' R U R' U' F'",
    "H3": "R U R' U R U L' U R' U' L",
    "H4": "F R U R' U' R U R' U' R U R' U' F'",
    "L1": "R' U2 R U R' U' R U R' U' R U R' U R",
    "L2": "R' U2 R' D' R U2 R' D R2",
    "L3": "R U2 R D R' U2 R D' R2",
    "L4": "F R' F' r U R U' r'",
    "L5": "x R' U R D' R' U' R D",
    "L6": "R' U' R U R' F' R U R' U' R' F R2",
    "P1": "R U2 R2 U' R2 U' R2 U2 R",
    "P2": "R' F2 R U2 R U2 R' F2 U' R U' R'",
    "P3": "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
    "P4": "R U R' U' R' F R2 U R' U' R U R' U' F'",
    "P5": "R U' L' U R' U L U L' U L",
    "P6": "R2 D' R U R' D R U R U' R' U R U R' U R",
    "S1": "R U R' U R U2 R'",
    "S2": "L' U2 L U2 R U' L' U L R'",
    "S3": "R2 D' R U2 R' D R2 U R' U R",
    "S4": "R U R' U R U' R D R' U' R D' R2",
    "S5": "R U' L' U R' U' L",
    "S6": "F' R U2 R' U2 R' F2 R U R U' R' F'",
    "T1": "R U2 R' U' R U' R2 U2 R U R' U R",
    "T2": "R' U R U2 R' L' U R U' L",
    "T3": "l' U' L U l F' L' F",
    "T4": "F R U R' U' R U' R' U' R U R' F'",
    "T5": "r U R' U' r' F R F'",
    "T6": "R' U R2 D r' U2 r D' R2 U' R",
    "U1": "R' U' R U' R' U2 R2 U R' U R U2 R'",
    "U2": "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
    "U3": "R2 D R' U2 R D' R' U2 R'",
    "U4": "F R U' R' U R U R' U R U' R' F'",
    "U5": "R2 D' R U2 R' D R U2 R",
    "U6": "R2 D' R U R' D R U R U' R' U' R",
  };

}
