class DefaultAlgs {
  static final pll = {
    "Aa": "x L2 D2 L' U' L D2 L' U L'",
    "Ab": "x' L2 D2 L U L' D2 L U' L",
    "E": "x' L' U L D' L' U' L D L' U' L D' L' U L D",
    "F": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "Ga": "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    "Gb": "R' U' R U D' R2 U R' U R U' R U' R2 D",
    "Gc": "R2 U' R U' R U R' U R2 U D' R U' R' D",
    "Gd": "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    "H": "M2 U M2 U2 M2 U M2",
    "Ja": "x R2 F R F' R U2 r' U r U2",
    "Jb": "R U R' F' R U R' U' R' F R2 U' R'",
    "Na": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "Nb": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "Ra": "R U' R' U' R U R D R' U' R D' R' U2 R'",
    "Rb": "R2 F R U R U' R' F' R U2 R' U2 R",
    "T": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "Ua": "M2 U M U2 M' U M2",
    "Ub": "M2 U' M U2 M' U' M2",
    "V": "R' U R' U' y R' F' R2 U' R' U R' F R F",
    "Y": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "Z": "M' U M2 U M2 U M' U2 M2",
  };
  static final oll = {
    "29": "R U R' U' R U' R' F' U' F R U R'",
    "30": "F R' F R2 U' R' U' R U R' F2",
    "41": "R U R' U R U2 R' F R U R' U' F'",
    "42": "R' U' R U' R' U2 R F R U R' U' F'",
    "39": "L F' L' U' L U F U' L'",
    "40": "R' F R U R' U' F' U R",
    "34": "R U R2 U' R' F R U R U' F'",
    "46": "R' U' R' F R F' U R",
    "28": "r U R' U' r' R U R U' R'",
    "57": "R U R' U' M' U R U' r'",
    "21": "R U2 R' U' R U R' U' R U' R'",
    "22": "R U2 R2 U' R2 U' R2 U2 R",
    "23": "R2 D' R U2 R' D R U2 R",
    "24": "r U R' U' r' F R F'",
    "25": "F' r U R' U' r' F R",
    "26": "R U2 R' U' R U' R'",
    "27": "R U R' U R U2 R'",
    "1": "R U2 R2 F R F' U2 R' F R F'",
    "2": "r U r' U2 r U2 R' U2 R U' r'",
    "3": "r' R2 U R' U r U2 r' U M'",
    "4": "M U' r U2 r' U' R U' R' M'",
    "17": "F R' F' R2 r' U R U' R' U' M'",
    "18": "r U R' U R U2 r2 U' R U' R' U2 r",
    "19": "r' R U R U R' U' M' R' F R F'",
    "20": "r U R' U' M2 U R U' R' U' M'",
    "9": "R U R' U' R' F R2 U R' U' F'",
    "10": "R U R' U R' F R F' R U2 R'",
    "35": "R U2 R2 F R F' R U2 R'",
    "37": "F R' F' R U R U' R'",
    "51": "F U R U' R' U R U' R' F'",
    "52": "R U R' U R U' B U' B' R'",
    "55": "R' F R U R U' R2 F' R2 U' R' U R U R'",
    "56": "r' U' r U' R' U R U' R' U R r' U r",
    "13": "F U R U' R2 F' R U R U' R'",
    "14": "R' F R U R' F' R F U' F'",
    "15": "l' U' l L' U' L U l' U l",
    "16": "r U r' R U R' U' r U' r'",
    "31": "R' U' F U R U' R' F' R",
    "32": "L U F' U' L' U L F L'",
    "43": "F' U' L' U L F",
    "44": "F U R U' R' F'",
    "47": "R' U' R' F R F' R' F R F' U R",
    "48": "F R U R' U' R U R' U' F'",
    "49": "r U' r2 U r2 U r2 U' r",
    "50": "r' U r2 U' r2 U' r2 U r'",
    "53": "l' U2 L U L' U' L U L' U l",
    "54": "r U2 R' U' R U R' U' R U' r'",
    "7": "r U R' U R U2 r'",
    "8": "l' U' L U' L' U2 l",
    "11": "r U R' U R' F R F' R U2 r'",
    "12": "M' R' U' R U' R' U2 R U' R r'",
    "5": "l' U2 L U L' U l",
    "6": "r U2 R' U' R U' r'",
    "33": "R U R' U' R' F R F'",
    "45": "F R U R' U' F'",
    "36": "L' U' L U' L' U L U L F' L' F",
    "38": "R U R' U R U' R' U' R' F R F'",
  };
  static final coll = {
    "AS1": "L' U' L U' L' U2 L",
    "AS2": "R' U2 F' R U R' U' R' F R2 U R' U R",
    "AS3": "R2 D R' U2 R D' R2 U' R U' R'",
    "AS4": "R' U' R U' R2 D' R U2 R' D R2",
    "AS5": "L' U R U' L U R'",
    "AS6": "R U' R' U2 R U' R' U2 R' D' R U R' D R",
    "H1": "R U R' U R U' R' U R U2 R'",
    "H2": "F R U' R' U R U2 R' U' R U R' U' F'",
    "H3": "R U R' U R U L' U R' U' L",
    "H4": "F R U R' U' R U R' U' R U R' U' F'",
    "L1": "R' U2 R U R' U' R U R' U' R U R' U R",
    "L2": "R' U2 R' D' R U2 R' D R2",
    "L3": "R U2 R D R' U2 R D' R2",
    "L4": "F R' F' r U R U' r'",
    "L5": "x R' U R D' R' U' R D",
    "L6": "R' U' R U R' F' R U R' U' R' F R2",
    "P1": "R U2 R2 U' R2 U' R2 U2 R",
    "P2": "R' F2 R U2 R U2 R' F2 U' R U' R'",
    "P3": "R' U' F' R U R' U' R' F R2 U2 R' U2 R",
    "P4": "R U R' U' R' F R2 U R' U' R U R' U' F'",
    "P5": "R U' L' U R' U L U L' U L",
    "P6": "R2 D' R U R' D R U R U' R' U R U R' U R",
    "S1": "R U R' U R U2 R'",
    "S2": "L' U2 L U2 R U' L' U L R'",
    "S3": "R2 D' R U2 R' D R2 U R' U R",
    "S4": "R U R' U R U' R D R' U' R D' R2",
    "S5": "R U' L' U R' U' L",
    "S6": "F' R U2 R' U2 R' F2 R U R U' R' F'",
    "T1": "R U2 R' U' R U' R2 U2 R U R' U R",
    "T2": "R' U R U2 R' L' U R U' L",
    "T3": "l' U' L U l F' L' F",
    "T4": "F R U R' U' R U' R' U' R U R' F'",
    "T5": "r U R' U' r' F R F'",
    "T6": "R' U R2 D r' U2 r D' R2 U' R",
    "U1": "R' U' R U' R' U2 R2 U R' U R U2 R'",
    "U2": "R' F R U' R' U' R U R' F' R U R' U' R' F R F' R",
    "U3": "R2 D R' U2 R D' R' U2 R'",
    "U4": "F R U' R' U R U R' U R U' R' F'",
    "U5": "R2 D' R U2 R' D R U2 R",
    "U6": "R2 D' R U R' D R U R U' R' U' R",
  };

  static final zbll = {
    "aS-FBBF-AsA": "",
    "aS-FBBF-AsC": "",
    "aS-FBBF-AsO": "",
    "aS-FBBF-CsA": "",
    "aS-FBBF-CsC": "",
    "aS-FBBF-CsO": "",
    "aS-FBBF-CxO": "",
    "aS-FBBF-OsA": "",
    "aS-FBBF-OsC": "",
    "aS-FBBF-OsO": "",
    "aS-FBBF-OxC": "",
    "aS-FBBF-OxO": "",
    "aS-FBFB-AsA": "",
    "aS-FBFB-AsC": "",
    "aS-FBFB-AsO": "",
    "aS-FBFB-CsA": "",
    "aS-FBFB-CsC": "",
    "aS-FBFB-CsO": "",
    "aS-FBFB-CxO": "",
    "aS-FBFB-OsA": "",
    "aS-FBFB-OsC": "",
    "aS-FBFB-OsO": "",
    "aS-FBFB-OxC": "",
    "aS-FBFB-OxO": "",
    "aS-FRFL-AsA": "",
    "aS-FRFL-AsC": "",
    "aS-FRFL-AsO": "",
    "aS-FRFL-CsA": "",
    "aS-FRFL-CsC": "",
    "aS-FRFL-CsO": "",
    "aS-FRFL-CxO": "",
    "aS-FRFL-OsA": "",
    "aS-FRFL-OsC": "",
    "aS-FRFL-OsO": "",
    "aS-FRFL-OxC": "",
    "aS-FRFL-OxO": "",
    "aS-FRLF-AsA": "",
    "aS-FRLF-AsC": "",
    "aS-FRLF-AsO": "",
    "aS-FRLF-CsA": "",
    "aS-FRLF-CsC": "",
    "aS-FRLF-CsO": "",
    "aS-FRLF-CxO": "",
    "aS-FRLF-OsA": "",
    "aS-FRLF-OsC": "",
    "aS-FRLF-OsO": "",
    "aS-FRLF-OxC": "",
    "aS-FRLF-OxO": "",
    "aS-LFRF-AsA": "",
    "aS-LFRF-AsC": "",
    "aS-LFRF-AsO": "",
    "aS-LFRF-CsA": "",
    "aS-LFRF-CsC": "",
    "aS-LFRF-CsO": "",
    "aS-LFRF-CxO": "",
    "aS-LFRF-OsA": "",
    "aS-LFRF-OsC": "",
    "aS-LFRF-OsO": "",
    "aS-LFRF-OxC": "",
    "aS-LFRF-OxO": "",
    "aS-RFFL-AsA": "",
    "aS-RFFL-AsC": "",
    "aS-RFFL-AsO": "",
    "aS-RFFL-CsA": "",
    "aS-RFFL-CsC": "",
    "aS-RFFL-CsO": "",
    "aS-RFFL-CxO": "",
    "aS-RFFL-OsA": "",
    "aS-RFFL-OsC": "",
    "aS-RFFL-OsO": "",
    "aS-RFFL-OxC": "",
    "aS-RFFL-OxO": "",
    "H-BBFF-AsA": "",
    "H-BBFF-AsC": "",
    "H-BBFF-AsO": "",
    "H-BBFF-CsC": "",
    "H-BBFF-CsO": "",
    "H-BBFF-CxO": "",
    "H-BBFF-OsO": "",
    "H-BBFF-OxO": "",
    "H-FBFB-AsA": "",
    "H-FBFB-AsC": "",
    "H-FBFB-AsO": "",
    "H-FBFB-CsO": "",
    "H-FBFB-CxO": "",
    "H-FBFB-OsC": "",
    "H-FBFB-OsO": "",
    "H-FBFB-OxC": "",
    "H-RFLF-AsA": "",
    "H-RFLF-AsC": "",
    "H-RFLF-AsO": "",
    "H-RFLF-CsA": "",
    "H-RFLF-CsC": "",
    "H-RFLF-CsO": "",
    "H-RFLF-CxO": "",
    "H-RFLF-OsA": "",
    "H-RFLF-OsC": "",
    "H-RFLF-OsO": "",
    "H-RFLF-OxC": "",
    "H-RFLF-OxO": "",
    "H-RLFF-AsA": "",
    "H-RLFF-AsC": "",
    "H-RLFF-AsO": "",
    "H-RLFF-CsA": "",
    "H-RLFF-CsC": "",
    "H-RLFF-CsO": "",
    "H-RLFF-CxO": "",
    "H-RLFF-OsA": "",
    "H-RLFF-OsC": "",
    "H-RLFF-OsO": "",
    "H-RLFF-OxC": "",
    "H-RLFF-OxO": "",
    "L-FBRL-AsA": "",
    "L-FBRL-AsC": "",
    "L-FBRL-AsO": "",
    "L-FBRL-CsA": "",
    "L-FBRL-CsC": "",
    "L-FBRL-CsO": "",
    "L-FBRL-CxO": "",
    "L-FBRL-OsA": "",
    "L-FBRL-OsC": "",
    "L-FBRL-OsO": "",
    "L-FBRL-OxC": "",
    "L-FBRL-OxO": "",
    "L-LBFF-AsA": "",
    "L-LBFF-AsC": "",
    "L-LBFF-AsO": "",
    "L-LBFF-CsA": "",
    "L-LBFF-CsC": "",
    "L-LBFF-CsO": "",
    "L-LBFF-CxO": "",
    "L-LBFF-OsA": "",
    "L-LBFF-OsC": "",
    "L-LBFF-OsO": "",
    "L-LBFF-OxC": "",
    "L-LBFF-OxO": "",
    "L-LFFB-AsA": "",
    "L-LFFB-AsC": "",
    "L-LFFB-AsO": "",
    "L-LFFB-CsA": "",
    "L-LFFB-CsC": "",
    "L-LFFB-CsO": "",
    "L-LFFB-CxO": "",
    "L-LFFB-OsA": "",
    "L-LFFB-OsC": "",
    "L-LFFB-OsO": "",
    "L-LFFB-OxC": "",
    "L-LFFB-OxO": "",
    "L-LFFR-AsA": "",
    "L-LFFR-AsC": "",
    "L-LFFR-AsO": "",
    "L-LFFR-CsA": "",
    "L-LFFR-CsC": "",
    "L-LFFR-CsO": "",
    "L-LFFR-CxO": "",
    "L-LFFR-OsA": "",
    "L-LFFR-OsC": "",
    "L-LFFR-OsO": "",
    "L-LFFR-OxC": "",
    "L-LFFR-OxO": "",
    "L-LRFF-AsA": "",
    "L-LRFF-AsC": "",
    "L-LRFF-AsO": "",
    "L-LRFF-CsA": "",
    "L-LRFF-CsC": "",
    "L-LRFF-CsO": "",
    "L-LRFF-CxO": "",
    "L-LRFF-OsA": "",
    "L-LRFF-OsC": "",
    "L-LRFF-OsO": "",
    "L-LRFF-OxC": "",
    "L-LRFF-OxO": "",
    "L-RFBL-AsA": "",
    "L-RFBL-AsC": "",
    "L-RFBL-AsO": "",
    "L-RFBL-CsA": "",
    "L-RFBL-CsC": "",
    "L-RFBL-CsO": "",
    "L-RFBL-CxO": "",
    "L-RFBL-OsA": "",
    "L-RFBL-OsC": "",
    "L-RFBL-OsO": "",
    "L-RFBL-OxC": "",
    "L-RFBL-OxO": "",
    "Pi-BFFB-AsA": "",
    "Pi-BFFB-AsC": "",
    "Pi-BFFB-AsO": "",
    "Pi-BFFB-CsA": "",
    "Pi-BFFB-CsC": "",
    "Pi-BFFB-CsO": "",
    "Pi-BFFB-CxO": "",
    "Pi-BFFB-OsA": "",
    "Pi-BFFB-OsC": "",
    "Pi-BFFB-OsO": "",
    "Pi-BFFB-OxC": "",
    "Pi-BFFB-OxO": "",
    "Pi-FBFB-AsA": "",
    "Pi-FBFB-AsC": "",
    "Pi-FBFB-AsO": "",
    "Pi-FBFB-CsA": "",
    "Pi-FBFB-CsC": "",
    "Pi-FBFB-CsO": "",
    "Pi-FBFB-CxO": "",
    "Pi-FBFB-OsA": "",
    "Pi-FBFB-OsC": "",
    "Pi-FBFB-OsO": "",
    "Pi-FBFB-OxC": "",
    "Pi-FBFB-OxO": "",
    "Pi-FRFL-AsA": "",
    "Pi-FRFL-AsC": "",
    "Pi-FRFL-AsO": "",
    "Pi-FRFL-CsA": "",
    "Pi-FRFL-CsC": "",
    "Pi-FRFL-CsO": "",
    "Pi-FRFL-CxO": "",
    "Pi-FRFL-OsA": "",
    "Pi-FRFL-OsC": "",
    "Pi-FRFL-OsO": "",
    "Pi-FRFL-OxC": "",
    "Pi-FRFL-OxO": "",
    "Pi-FRLF-AsA": "",
    "Pi-FRLF-AsC": "",
    "Pi-FRLF-AsO": "",
    "Pi-FRLF-CsA": "",
    "Pi-FRLF-CsC": "",
    "Pi-FRLF-CsO": "",
    "Pi-FRLF-CxO": "",
    "Pi-FRLF-OsA": "",
    "Pi-FRLF-OsC": "",
    "Pi-FRLF-OsO": "",
    "Pi-FRLF-OxC": "",
    "Pi-FRLF-OxO": "",
    "Pi-LFRF-AsA": "",
    "Pi-LFRF-AsC": "",
    "Pi-LFRF-AsO": "",
    "Pi-LFRF-CsA": "",
    "Pi-LFRF-CsC": "",
    "Pi-LFRF-CsO": "",
    "Pi-LFRF-CxO": "",
    "Pi-LFRF-OsA": "",
    "Pi-LFRF-OsC": "",
    "Pi-LFRF-OsO": "",
    "Pi-LFRF-OxC": "",
    "Pi-LFRF-OxO": "",
    "Pi-RFFL-AsA": "",
    "Pi-RFFL-AsC": "",
    "Pi-RFFL-AsO": "",
    "Pi-RFFL-CsA": "",
    "Pi-RFFL-CsC": "",
    "Pi-RFFL-CsO": "",
    "Pi-RFFL-CxO": "",
    "Pi-RFFL-OsA": "",
    "Pi-RFFL-OsC": "",
    "Pi-RFFL-OsO": "",
    "Pi-RFFL-OxC": "",
    "Pi-RFFL-OxO": "",
    "S-FBBF-AsA": "",
    "S-FBBF-AsC": "",
    "S-FBBF-AsO": "",
    "S-FBBF-CsA": "",
    "S-FBBF-CsC": "",
    "S-FBBF-CsO": "",
    "S-FBBF-CxO": "",
    "S-FBBF-OsA": "",
    "S-FBBF-OsC": "",
    "S-FBBF-OsO": "",
    "S-FBBF-OxC": "",
    "S-FBBF-OxO": "",
    "S-FBFB-AsA": "",
    "S-FBFB-AsC": "",
    "S-FBFB-AsO": "",
    "S-FBFB-CsA": "",
    "S-FBFB-CsC": "",
    "S-FBFB-CsO": "",
    "S-FBFB-CxO": "",
    "S-FBFB-OsA": "",
    "S-FBFB-OsC": "",
    "S-FBFB-OsO": "",
    "S-FBFB-OxC": "",
    "S-FBFB-OxO": "",
    "S-FLFR-AsA": "",
    "S-FLFR-AsC": "",
    "S-FLFR-AsO": "",
    "S-FLFR-CsA": "",
    "S-FLFR-CsC": "",
    "S-FLFR-CsO": "",
    "S-FLFR-CxO": "",
    "S-FLFR-OsA": "",
    "S-FLFR-OsC": "",
    "S-FLFR-OsO": "",
    "S-FLFR-OxC": "",
    "S-FLFR-OxO": "",
    "S-FLRF-AsA": "",
    "S-FLRF-AsC": "",
    "S-FLRF-AsO": "",
    "S-FLRF-CsA": "",
    "S-FLRF-CsC": "",
    "S-FLRF-CsO": "",
    "S-FLRF-CxO": "",
    "S-FLRF-OsA": "",
    "S-FLRF-OsC": "",
    "S-FLRF-OsO": "",
    "S-FLRF-OxC": "",
    "S-FLRF-OxO": "",
    "S-LFFR-AsA": "",
    "S-LFFR-AsC": "",
    "S-LFFR-AsO": "",
    "S-LFFR-CsA": "",
    "S-LFFR-CsC": "",
    "S-LFFR-CsO": "",
    "S-LFFR-CxO": "",
    "S-LFFR-OsA": "",
    "S-LFFR-OsC": "",
    "S-LFFR-OsO": "",
    "S-LFFR-OxC": "",
    "S-LFFR-OxO": "",
    "S-LFRF-AsA": "",
    "S-LFRF-AsC": "",
    "S-LFRF-AsO": "",
    "S-LFRF-CsA": "",
    "S-LFRF-CsC": "",
    "S-LFRF-CsO": "",
    "S-LFRF-CxO": "",
    "S-LFRF-OsA": "",
    "S-LFRF-OsC": "",
    "S-LFRF-OsO": "",
    "S-LFRF-OxC": "",
    "S-LFRF-OxO": "",
    "T-BBFF-AsA": "",
    "T-BBFF-AsC": "",
    "T-BBFF-AsO": "",
    "T-BBFF-CsA": "",
    "T-BBFF-CsC": "",
    "T-BBFF-CsO": "",
    "T-BBFF-CxO": "",
    "T-BBFF-OsA": "",
    "T-BBFF-OsC": "",
    "T-BBFF-OsO": "",
    "T-BBFF-OxC": "",
    "T-BBFF-OxO": "",
    "T-FBFB-AsA": "",
    "T-FBFB-AsC": "",
    "T-FBFB-AsO": "",
    "T-FBFB-CsA": "",
    "T-FBFB-CsC": "",
    "T-FBFB-CsO": "",
    "T-FBFB-CxO": "",
    "T-FBFB-OsA": "",
    "T-FBFB-OsC": "",
    "T-FBFB-OsO": "",
    "T-FBFB-OxC": "",
    "T-FBFB-OxO": "",
    "T-FFLR-AsA": "",
    "T-FFLR-AsC": "",
    "T-FFLR-AsO": "",
    "T-FFLR-CsA": "",
    "T-FFLR-CsC": "",
    "T-FFLR-CsO": "",
    "T-FFLR-CxO": "",
    "T-FFLR-OsA": "",
    "T-FFLR-OsC": "",
    "T-FFLR-OsO": "",
    "T-FFLR-OxC": "",
    "T-FFLR-OxO": "",
    "T-FLFR-AsA": "",
    "T-FLFR-AsC": "",
    "T-FLFR-AsO": "",
    "T-FLFR-CsA": "",
    "T-FLFR-CsC": "",
    "T-FLFR-CsO": "",
    "T-FLFR-CxO": "",
    "T-FLFR-OsA": "",
    "T-FLFR-OsC": "",
    "T-FLFR-OsO": "",
    "T-FLFR-OxC": "",
    "T-FLFR-OxO": "",
    "T-RFLF-AsA": "",
    "T-RFLF-AsC": "",
    "T-RFLF-AsO": "",
    "T-RFLF-CsA": "",
    "T-RFLF-CsC": "",
    "T-RFLF-CsO": "",
    "T-RFLF-CxO": "",
    "T-RFLF-OsA": "",
    "T-RFLF-OsC": "",
    "T-RFLF-OsO": "",
    "T-RFLF-OxC": "",
    "T-RFLF-OxO": "",
    "T-RLFF-AsA": "",
    "T-RLFF-AsC": "",
    "T-RLFF-AsO": "",
    "T-RLFF-CsA": "",
    "T-RLFF-CsC": "",
    "T-RLFF-CsO": "",
    "T-RLFF-CxO": "",
    "T-RLFF-OsA": "",
    "T-RLFF-OsC": "",
    "T-RLFF-OsO": "",
    "T-RLFF-OxC": "",
    "T-RLFF-OxO": "",
    "U-BBFF-AsA": "",
    "U-BBFF-AsC": "",
    "U-BBFF-AsO": "",
    "U-BBFF-CsA": "",
    "U-BBFF-CsC": "",
    "U-BBFF-CsO": "",
    "U-BBFF-CxO": "",
    "U-BBFF-OsA": "",
    "U-BBFF-OsC": "",
    "U-BBFF-OsO": "",
    "U-BBFF-OxC": "",
    "U-BBFF-OxO": "",
    "U-BFFB-AsA": "",
    "U-BFFB-AsC": "",
    "U-BFFB-AsO": "",
    "U-BFFB-CsA": "",
    "U-BFFB-CsC": "",
    "U-BFFB-CsO": "",
    "U-BFFB-CxO": "",
    "U-BFFB-OsA": "",
    "U-BFFB-OsC": "",
    "U-BFFB-OsO": "",
    "U-BFFB-OxC": "",
    "U-BFFB-OxO": "",
    "U-FFLR-AsA": "",
    "U-FFLR-AsC": "",
    "U-FFLR-AsO": "",
    "U-FFLR-CsA": "",
    "U-FFLR-CsC": "",
    "U-FFLR-CsO": "",
    "U-FFLR-CxO": "",
    "U-FFLR-OsA": "",
    "U-FFLR-OsC": "",
    "U-FFLR-OsO": "",
    "U-FFLR-OxC": "",
    "U-FFLR-OxO": "",
    "U-FRLF-AsA": "",
    "U-FRLF-AsC": "",
    "U-FRLF-AsO": "",
    "U-FRLF-CsA": "",
    "U-FRLF-CsC": "",
    "U-FRLF-CsO": "",
    "U-FRLF-CxO": "",
    "U-FRLF-OsA": "",
    "U-FRLF-OsC": "",
    "U-FRLF-OsO": "",
    "U-FRLF-OxC": "",
    "U-FRLF-OxO": "",
    "U-LFFR-AsA": "",
    "U-LFFR-AsC": "",
    "U-LFFR-AsO": "",
    "U-LFFR-CsA": "",
    "U-LFFR-CsC": "",
    "U-LFFR-CsO": "",
    "U-LFFR-CxO": "",
    "U-LFFR-OsA": "",
    "U-LFFR-OsC": "",
    "U-LFFR-OsO": "",
    "U-LFFR-OxC": "",
    "U-LFFR-OxO": "",
    "U-LRFF-AsA": "",
    "U-LRFF-AsC": "",
    "U-LRFF-AsO": "",
    "U-LRFF-CsA": "",
    "U-LRFF-CsC": "",
    "U-LRFF-CsO": "",
    "U-LRFF-CxO": "",
    "U-LRFF-OsA": "",
    "U-LRFF-OsC": "",
    "U-LRFF-OsO": "",
    "U-LRFF-OxC": "",
    "U-LRFF-OxO": "",
  };

}
